
#MYSQL
spring:
  datasource:
    url: jdbc:mysql://1.15.61.30:3306/change_project
    username: melody
    password: mysql_melody
    driver-class-name: com.mysql.cj.jdbc.Driver
  #controller返回html
  freemarker:
    suffix: .html
    cache: false  #页面不加载缓存，修改即时生效
  #热部署
  devtools:
    restart:
      enabled: true #设置开启热部署
      additional-paths: src/main/java #重启目录
#      exclude:   #排除目录
#项目启动
server:
  servlet:
    context-path: /change       #项目访问路径
  port: 8080                    #服务器HTTP端口

#mybatis配置
mybatis:
  type-aliases-package: com.vincent.change.entity.userinfo
  mapper-locations: classpath:mapper/*.xml